import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'
import RightBar from "./components/RightBar";
import LeftBar from "./components/LeftBar";
import {Providers} from './components/Provider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sql Playground",
  icons: {
    icon: "/squareImage copy.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` `}
      > 
          <Providers>
          <Navbar/>
          <div className="flex flex-row">
            <LeftBar/>
              {children} 
          <RightBar/>
          </div>
         </Providers>

      </body>
    </html>
  );
}
